### ISSUE TITLE
Add native EteSync support

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/friends#8]
**EteSync** "Secure, end-to-end encrypted, and privacy respecting sync for your contacts, calendars and tasks." Reference to the discussion in the Planner repository alainm23/planner#307 (comment)

I have no experience with EteSync myself, but I find the idea of end-to-end encryption of sensitive data in the context of elementary OS very useful.
This issue should provide room for discussion. Consciously also about possible alternatives, how the desired qualities can be provided independently of certain products.

**Comment by 4jNsY6fCVqZv** [comment]
I have no experience with EteSync myself, but I find the idea of end-to-end encryption of sensitive data in the context of elementary OS very useful.
This issue should provide room for discussion. Consciously also about possible alternatives, how the desired qualities can be provided independently of certain products.

**Comment by danrabbit** [comment]
Closing as "Out of Scope" because Friends uses LibFolks to abstract backends. An EteSync backend would need to be written for Folks.

**Comment by 4jNsY6fCVqZv** [comment]
https://wiki.gnome.org/Projects/Folks says:
"libfolks is a library that aggregates people from multiple sources (eg, Telepathy connection managers for IM contacts, Evolution Data Server for local contacts, etc.) to create metacontacts."
--> How is the example with EDS to be understood in this context? Does EDS also use the libfolks library for contact management?

**Comment by 4jNsY6fCVqZv** [comment]
Daniel, I'm a little confused.
GNOME Contacts also uses libfolks. https://wiki.gnome.org/Apps/Contacts
And with GNOME Contacts, EteSync should work. 
https://github.com/etesync/etesync-dav#evolution--gnome-calendar--gnome-contacts
Maybe @tasn knows more?

**Comment by cassidyjames** [comment]
If it works in GNOME Contacts, the same solution should work here by adding it through Evolution.

**Comment by tasn** [comment]
EteSync support will be added to EDS this summer: https://blog.etesync.com/summer-internship-opportunities-etesync-projects-in-both-gsoc-and-outreachy/

I'm not familiar with libfolks so not sure whether this is relevant for this feature request or not.

**Comment by tintou** [comment]
libfolks uses evolution-data-server

**Comment by tasn** [comment]
Great, so I guess that would be sufficient.

**Comment by 4jNsY6fCVqZv** [comment]
https://blog.etesync.com/gnome-and-kde-etesync-projects-accepted-to-gsoc/

**Comment by tasn** [comment]
EteSync is now supported directly in GNOME, so I guess it should just work here!
